# Generated by Django 4.0.6 on 2023-09-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='collection_name',
        ),
    ]
