# Generated by Django 4.0.6 on 2023-09-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0002_rename_name_series_collection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='name',
            new_name='models_name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='collection_name',
            new_name='series_name',
        ),
    ]
