# Generated by Django 4.0.6 on 2023-09-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0003_rename_name_collection_collection_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
    ]
