# Generated by Django 4.0.6 on 2023-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0005_rename_brand_id_collection_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surfacefisnish',
            new_name='Surfacefinish',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='surfacefisnish_id',
            new_name='surfacefinish_id',
        ),
        migrations.RemoveField(
            model_name='surfacefinish',
            name='name',
        ),
        migrations.AddField(
            model_name='surfacefinish',
            name='surface_name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
