# Generated by Django 4.0.6 on 2023-09-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0006_rename_surfacefisnish_surfacefinish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
