# Generated by Django 4.0.6 on 2023-09-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0009_rename_collection_id_series_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(max_length=255)),
                ('model_image', models.FileField(blank=True, null=True, upload_to='model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.AddField(
            model_name='model',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lianhin.series'),
        ),
        migrations.AddField(
            model_name='model',
            name='surfacefinish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lianhin.surfacefinish'),
        ),
    ]
