# Generated by Django 4.0.6 on 2023-09-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lianhin', '0011_alter_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='surfacefinish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lianhin.surfacefinish'),
        ),
    ]
